package com.vm.demo.vo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-03-18T22:32:12.827-04:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://vo.demo.vm.com/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @WebMethod
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://vo.demo.vm.com/", className = "com.vm.demo.vo.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://vo.demo.vm.com/", className = "com.vm.demo.vo.UpdateCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.vm.demo.vo.Customer updateCustomer(
        @WebParam(name = "customer", targetNamespace = "")
        com.vm.demo.vo.Customer customer
    ) throws NoSuchCustomerException;

    @WebMethod
    @RequestWrapper(localName = "getCustomersByName", targetNamespace = "http://vo.demo.vm.com/", className = "com.vm.demo.vo.GetCustomersByName")
    @ResponseWrapper(localName = "getCustomersByNameResponse", targetNamespace = "http://vo.demo.vm.com/", className = "com.vm.demo.vo.GetCustomersByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.vm.demo.vo.Customer> getCustomersByName(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    ) throws NoSuchCustomerException;
}
