
package com.vm.demo.vo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-03-18T22:32:12.803-04:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "NoSuchCustomer", targetNamespace = "http://vo.demo.vm.com/")
public class NoSuchCustomerException extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vm.demo.vo.NoSuchCustomer noSuchCustomer;

    public NoSuchCustomerException() {
        super();
    }
    
    public NoSuchCustomerException(String message) {
        super(message);
    }
    
    public NoSuchCustomerException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchCustomerException(String message, com.vm.demo.vo.NoSuchCustomer noSuchCustomer) {
        super(message);
        this.noSuchCustomer = noSuchCustomer;
    }

    public NoSuchCustomerException(String message, com.vm.demo.vo.NoSuchCustomer noSuchCustomer, Throwable cause) {
        super(message, cause);
        this.noSuchCustomer = noSuchCustomer;
    }

    public com.vm.demo.vo.NoSuchCustomer getFaultInfo() {
        return this.noSuchCustomer;
    }
}
